Roku Remote Control (#59)
* Added configuration for host and sendRemoteCommand function

* Update host for remote

We look for the host in the following order:
1. It has been set in users configuration as `brightscript.remoteControl.host`
2. If not, it will prompt for the host IP

It will also get set or updated any time the debug launches

You can toggle the remote control by setitng a keybinding on `extension.brightscript.toggleRemote`

You can also set keybindings to send commands like:
```
{
    "key": "Backspace",
    "command": "extension.brightscript.sendRemoteCommand",
    "args": "Back",
    "when": "isInRemoteMode"
}
```

* Added Status bar color change and mesages when Remote is Active

* Clean up on activation

* Prompt for host when not set on debug launch

* Added documentation for the Roku remote

* Cleaned up code to pass linting ;)

* trying possible bug fix

src/BrightScriptCommands.ts:101:9 - error TS2322: Type '{}' is not assignable to type 'string'.

101         this.host = await this.context.workspaceState.get('remoteHost');

* Only update the current workspace’s settings when changing the bar color

* Removed the need to toggle the remote on and off

Also registered the basic 11 remote key commands and added default keybindings for them

* Added Roku Text send from popup text dialog

pressing `cmd+k` and you get a popup which you can input text and it will send the text to the roku

* lint cleanup

* Updated Documentation

Also changed the play button to cmd+Enter instead of cmd+p because it conflicted with the Command Palette

* Added Backspace and Updated documentation

* After text input, put focus on Output

* Changed command to `workbench.action.focusPanel`